---@class Enemy
---@field health number
---@field name string
---@field attack number
---@field initiative number

---@class Boss
---@field health number
---@field name string
---@field attack number
---@field initiative number
---@field spell Spell
